Ext.define('MyDesktop.models.ModeloDesgloceCumplimientoDias', {
	extend: 'Ext.data.Model',
	fields: [
	{name: 'descripcion', type: 'string'},
	{name: 'dia01',type: 'float'},
	{name: 'dia02',type: 'float'},
	{name: 'dia03',type: 'float'},
	{name: 'dia04',type: 'float'},
	{name: 'dia05',type: 'float'},
	{name: 'dia06',type: 'float'},
	{name: 'dia07',type: 'float'},
	{name: 'dia08',type: 'float'},
	{name: 'dia09',type: 'float'},
	{name: 'dia10',type: 'float'},
	{name: 'dia11',type: 'float'},
	{name: 'dia12',type: 'float'},
	{name: 'dia13',type: 'float'},
	{name: 'dia14',type: 'float'},
	{name: 'dia15',type: 'float'},
	{name: 'dia16',type: 'float'},
	{name: 'dia17',type: 'float'},
	{name: 'dia18',type: 'float'},
	{name: 'dia19',type: 'float'},
	{name: 'dia20',type: 'float'},
	{name: 'dia21',type: 'float'},
	{name: 'dia22',type: 'float'},
	{name: 'dia23',type: 'float'},
	{name: 'dia24',type: 'float'},
	{name: 'dia25',type: 'float'},
	{name: 'dia26',type: 'float'},
	{name: 'dia27',type: 'float'},
	{name: 'dia28',type: 'float'},
	{name: 'dia29',type: 'float'},
	{name: 'dia30',type: 'float'},
	{name: 'dia31',type: 'float'}
	]
});