package com.ws.interchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-04-04T00:55:33.447-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "InterchangeInfoService", 
                  wsdlLocation = "http://localhost:8010/ws-interchange/services/interchangeinfo?wsdl",
                  targetNamespace = "http://interchange.ws.com/") 
public class InterchangeInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://interchange.ws.com/", "InterchangeInfoService");
    public final static QName InterchangeInfoPort = new QName("http://interchange.ws.com/", "InterchangeInfoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8010/ws-interchange/services/interchangeinfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterchangeInfoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-interchange/services/interchangeinfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterchangeInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterchangeInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    

    public InterchangeInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InterchangeSEI
     */
    @WebEndpoint(name = "InterchangeInfoPort")
    public InterchangeSEI getInterchangeInfoPort() {
        return super.getPort(InterchangeInfoPort, InterchangeSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterchangeSEI
     */
    @WebEndpoint(name = "InterchangeInfoPort")
    public InterchangeSEI getInterchangeInfoPort(WebServiceFeature... features) {
        return super.getPort(InterchangeInfoPort, InterchangeSEI.class, features);
    }

}
