var  ESTATUS_INACTIVA =0;
var  ESTATUS_ACTIVA =10;
var  ESTATUS_TRANSFORMACION_CONVENIO=11;
var  ESTATUS_EN_DOCUMENTACION =20;//Estado con el que se transforma la cotizacion a convenio
var  ESTATUS_REVISION =30;
var  ESTATUS_AUTORIZADO =40;
var  ESTATUS_CERRADO =90;
var  ESTATUS_CANCELADO =90;