Ext.define('MyDesktop.models.ModeloConvenios', {
        extend: 'Ext.data.Model',
		fields: [
		   {name: 'idcliente', type: 'string'},
		   {name: 'idconvenio', type: 'string'},
		   {name: 'idcotizacionorigen', type: 'string'},
		   {name: 'clientelicitacion', type: 'string'},
		   {name: 'tipo_contrato', type: 'string'},
		   
		   {name: 'estatus', type: 'string'},
		   {name: 'representantelegal', type: 'string'},
		   {name: 'idtipoconvenio', type: 'string'},
		   {name: 'idoficinacontrol', type: 'string'},
		   {name: 'idcondicionpago', type: 'string'},
		   {name: 'idmetodopago', type: 'string'},
		   {name: 'idunidadadm', type: 'string'},
		   {name: 'idtarifa', type: 'string'},
		   {name: 'idtarifarango', type: 'string'},
		   {name: 'idpoblacionpago', type: 'string'},
		   {name: 'idformapago', type: 'string'},
		   {name: 'idclientelicitacion', type: 'string'},
		   {name: 'iddescuento', type: 'string'},
		   {name: 'fechadocumento', type: 'string'},
		   {name: 'tipo_precios', type: 'string'},
		   {name: 'rangoenvios', type: 'string'},
		   {name: 'idrangoenvios', type: 'string'},
		   {name: 'rangoenvios', type: 'string'},
		   

		   {name: 'fechainicio', type: 'string'},
		   {name: 'fechaactivacion', type: 'string'},
		   {name: 'fechatermino', type: 'string'},  
		   {name: 'fecharevision', type: 'string'},  
		   
		   {name: 'nombre', type: 'string'},
		   {name: 'descripcion', type: 'string'},
		   {name: 'observacion', type: 'string'},
		   
		   {name: 'razonsocial_cte', type: 'string'},
		   {name: 'contacto_cte', type: 'string'},
		   
		   {name: 'numcliente', type: 'string'},
		   {name: 'calle_cte', type: 'string'},
		   {name: 'numinterior_cte', type: 'string'},
		   {name: 'numexterior_cte', type: 'string'},
		   {name: 'cp_cte', type: 'string'},
		   {name: 'colonia_cte', type: 'string'},
		   {name: 'municipio_cte', type: 'string'},
		   {name: 'estado_cte', type: 'string'},
		   {name: 'telefono_cte', type: 'string'},
		   {name: 'movil_cte', type: 'string'},
		   {name: 'email_cte', type: 'string'},
		   {name: 'credito', type: 'integer'},

		   {name: 'rfc', type: 'string'},
		   {name: 'cuentabancaria', type: 'string'},
		   {name: 'nombrebanco', type: 'string'},
		   {name: 'diasrevision', type: 'string'},
		   {name: 'diaspago', type: 'string'},
		   
		   {name: 'calle_rev', type: 'string'},
		   {name: 'numinterior_rev', type: 'string'},
		   {name: 'numexterior_rev', type: 'string'},
		   {name: 'cp_rev', type: 'string'},
		   {name: 'colonia_rev', type: 'string'},
		   {name: 'municipio_rev', type: 'string'},
		   {name: 'estado_rev', type: 'string'},
		   {name: 'responsable_rev', type: 'string'},
		   {name: 'telefono_rev', type: 'string'},
		   {name: 'movil_rev', type: 'string'},
		   {name: 'email_resp_rev', type: 'string'},

		   {name: 'clientefirma', type: 'string'},
		   {name: 'gerentecomercialfirma', type: 'string'},
		   {name: 'jefezonafirma', type: 'string'},
		   {name: 'coordinadorcreditocobfirma', type: 'string'},
		   {name: 'directoradmfinanzasfirma', type: 'string'},

		   {name: 'responsable_pago', type: 'string'},
		   {name: 'email_resp_pago', type: 'string'},
		   {name: 'estadoactualdoc', type: 'string'},
		   {name: 'estatus', type: 'string'},
		   {name: 'login', type: 'string'},

		   {name: 'descripcionOficinacontrol', type: 'string'},
		   {name: 'descripcionTipoconvenio', type: 'string'},
		   {name: 'descripcionFormapago', type: 'string'},
		   {name: 'descripcionMetodopago', type: 'string'},
		   {name: 'descripcionCliente', type: 'string'},
		   {name: 'descripcionPoblacionpago', type: 'string'},
		   {name: 'descripcionCondicionpago', type: 'string'},
		   {name: 'descripcionDescuento', type: 'string'},
		   {name: 'descripcionTarifarango', type: 'string'},
		   {name: 'descripcionUnidadadm', type: 'string'},
		   {name: 'descripcionTipoConvenio', type: 'string'},
		   {name: 'tipocierre', type: 'string'},
		   {name: 'descripciontipocierre', type: 'string'},
		   {name: 'ejecutivoventasfirma', type: 'string'},
		   
		   /* DATOS SEGURO */
		   {name: 'asegura', type: 'string'},
		   {name: 'nombre_seguro', type: 'string'},
		   {name: 'porcentaje_seguro', type: 'string'}

		]
});