Ext.define('MyDesktop.models.ModeloRecolecciones', {
        extend: 'Ext.data.Model',
		fields: [
			{name: 'idrecoleccion'},
			{name: 'idregistro'},
			{name: 'razonsocial'}, 
			{name: 'razonsocialcliente'}, 
			{name: 'departamento'}, 
			{name: 'celularsolicita'}, 
			{name: 'numoficina'}, 
			{name: 'manifiesto'}, 
			
			{name: 'preguntarpor'}, 
			{name: 'calle'},
			{name: 'cp'},
			{name: 'colonia'},
			{name: 'municipio'},
			{name: 'estado'},
			{name: 'telefono'},
			{name: 'celular'}, 
			{name: 'contenido'}, 
			{name: 'observacion'},
			{name: 'cantidadpzas'}, 
			{name: 'pesokg'}, 
			{name: 'pesototal'},
			{name: 'alto'},
			{name: 'ancho'}, 
			{name: 'largo'}, 
			{name: 'volumen'}, 
			{name: 'fecharecol'},
			{name:'rutaasignada'},
			{name:'plaza'},
			{name:'estatus'},
			{name:'quiensolicita'},
			{name:'telefonosolicita'},
			{name:'correosolicita'},
			{name:'numcliente'},
			{name:'contrato'},
			{name:'email'},
			{name:'idsolicitud'},
			{name:'fechainicio'},
			{name:'fechafin'},
			{name:'descripciontiposolicitud'},
			{name:'descripcionempaque'},
			{name:'idtiporecol', type: 'string'},
			{name:'numempleado', type: 'string'},
			{name:'latitud', type: 'string'},
			{name:'longitud', type: 'string'},
			
			
			{name:'idempaque', type: 'string'}
		  
		]
});