
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ws.interchange;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-04-04T00:55:33.347-05:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "InterchangeInfoService",
                      portName = "InterchangeInfoPort",
                      targetNamespace = "http://interchange.ws.com/",
                      wsdlLocation = "http://localhost:8080/ws-interchange/services/interchangeinfo?wsdl",
                      endpointInterface = "com.ws.interchange.InterchangeSEI")
                      
public class InterchangeSEIImpl implements InterchangeSEI {

    private static final Logger LOG = Logger.getLogger(InterchangeSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ws.interchange.InterchangeSEI#procesa(java.util.List<java.lang.String>  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<java.lang.String> procesa(java.util.List<java.lang.String> arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation procesa");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1855913067";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ws.interchange.InterchangeSEI#procesaPlaza(java.util.List<java.lang.String>  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.util.List<java.lang.String> procesaPlaza(java.util.List<java.lang.String> arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation procesaPlaza");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal597829490";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ws.interchange.InterchangeSEI#isCorrectServer(java.lang.String  arg0 )*
     */
    public boolean isCorrectServer(java.lang.String arg0) { 
        LOG.info("Executing operation isCorrectServer");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
