package com.ws.interchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-04-04T00:55:33.400-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://interchange.ws.com/", name = "InterchangeSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface InterchangeSEI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "procesa", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.Procesa")
    @WebMethod
    @ResponseWrapper(localName = "procesaResponse", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.ProcesaResponse")
    public java.util.List<java.lang.String> procesa(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "procesaPlaza", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.ProcesaPlaza")
    @WebMethod
    @ResponseWrapper(localName = "procesaPlazaResponse", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.ProcesaPlazaResponse")
    public java.util.List<java.lang.String> procesaPlaza(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isCorrectServer", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.IsCorrectServer")
    @WebMethod
    @ResponseWrapper(localName = "isCorrectServerResponse", targetNamespace = "http://interchange.ws.com/", className = "com.ws.interchange.IsCorrectServerResponse")
    public boolean isCorrectServer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
