
package com.ws.interchange;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-04-04T00:55:32.987-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class InterchangeSEI_InterchangeInfoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://interchange.ws.com/", "InterchangeInfoService");

    private InterchangeSEI_InterchangeInfoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InterchangeInfoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InterchangeInfoService ss = new InterchangeInfoService(wsdlURL, SERVICE_NAME);
        InterchangeSEI port = ss.getInterchangeInfoPort();  
        
        {
        System.out.println("Invoking procesa...");
        java.util.List<java.lang.String> _procesa_arg0 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _procesa_arg0Val1 = "_procesa_arg0Val-879640252";
        _procesa_arg0.add(_procesa_arg0Val1);
        java.util.List<java.lang.String> _procesa_arg1 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _procesa_arg1Val1 = "_procesa_arg1Val-256390618";
        _procesa_arg1.add(_procesa_arg1Val1);
        java.util.List<java.lang.String> _procesa__return = port.procesa(_procesa_arg0, _procesa_arg1);
        System.out.println("procesa.result=" + _procesa__return);


        }
        {
        System.out.println("Invoking procesaPlaza...");
        java.util.List<java.lang.String> _procesaPlaza_arg0 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _procesaPlaza_arg0Val1 = "_procesaPlaza_arg0Val-1859833281";
        _procesaPlaza_arg0.add(_procesaPlaza_arg0Val1);
        java.lang.String _procesaPlaza_arg1 = "_procesaPlaza_arg134228312";
        java.lang.String _procesaPlaza_arg2 = "_procesaPlaza_arg2-1062869474";
        java.util.List<java.lang.String> _procesaPlaza__return = port.procesaPlaza(_procesaPlaza_arg0, _procesaPlaza_arg1, _procesaPlaza_arg2);
        System.out.println("procesaPlaza.result=" + _procesaPlaza__return);


        }
        {
        System.out.println("Invoking isCorrectServer...");
        java.lang.String _isCorrectServer_arg0 = "_isCorrectServer_arg02050874662";
        boolean _isCorrectServer__return = port.isCorrectServer(_isCorrectServer_arg0);
        System.out.println("isCorrectServer.result=" + _isCorrectServer__return);


        }

        System.exit(0);
    }

}
