
package com.ws.interchange.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Wed Apr 04 00:53:29 CDT 2012
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "isCorrectServerResponse", namespace = "http://interchange.ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isCorrectServerResponse", namespace = "http://interchange.ws.com/")

public class IsCorrectServerResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

