
package com.ws.interchange.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Wed Apr 04 00:53:29 CDT 2012
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "procesaPlaza", namespace = "http://interchange.ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procesaPlaza", namespace = "http://interchange.ws.com/", propOrder = {"arg0", "arg1", "arg2"})

public class ProcesaPlaza {

    @XmlElement(name = "arg0")
    private String[] arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public String[] getArg0() {
        return this.arg0;
    }

    public void setArg0(String[] newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

