
package com.ws.interchange.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Wed Apr 04 00:53:29 CDT 2012
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "procesa", namespace = "http://interchange.ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procesa", namespace = "http://interchange.ws.com/", propOrder = {"arg0", "arg1"})

public class Procesa {

    @XmlElement(name = "arg0")
    private String[] arg0;
    @XmlElement(name = "arg1")
    private String[] arg1;

    public String[] getArg0() {
        return this.arg0;
    }

    public void setArg0(String[] newArg0)  {
        this.arg0 = newArg0;
    }

    public String[] getArg1() {
        return this.arg1;
    }

    public void setArg1(String[] newArg1)  {
        this.arg1 = newArg1;
    }

}

