Ext.define('MyDesktop.store.StoreTemplateCampoDisponible', {
        extend: 'Ext.data.Store',
		fields: ['idtipo', 'descripcion'],
		data : [
		        {"idtipo":"", "descripcion":"Vacio"},
		        {"idtipo":"remesa", "descripcion":"remesa"},//idguiamultiple
				{"idtipo":"derresevados", "descripcion":"derresevados"},
				{"idtipo":"reimpresion", "descripcion":"reimpresion"},
				{"idtipo":"infoenvio", "descripcion":"infoenvio"},
				{"idtipo":"ancho", "descripcion":"ancho"},
				{"idtipo":"largo", "descripcion":"largo"},
				{"idtipo":"alto", "descripcion":"alto"},
				{"idtipo":"guiarapida", "descripcion":"guiarapida"},
				{"idtipo":"fechaimpresion", "descripcion":"fechaimpresion"},
				{"idtipo":"fechahoraimpresion", "descripcion":"fechahoraimpresion"},
				{"idtipo":"idenvio", "descripcion":"idenvio"},
				{"idtipo":"guiainternacional", "descripcion":"guiainternacional"},
				{"idtipo":"rutaentrega", "descripcion":"rutaentrega"},
				{"idtipo":"descservicio", "descripcion":"descservicio"},
				{"idtipo":"empresarem", "descripcion":"empresarem"},
				{"idtipo":"atencionrem", "descripcion":"atencionrem"},
				{"idtipo":"direccionrem", "descripcion":"direccionrem"},
				{"idtipo":"coloniarem", "descripcion":"coloniarem"},
				{"idtipo":"municipiorem", "descripcion":"municipiorem"},
				{"idtipo":"estadorem", "descripcion":"estadorem"},
				{"idtipo":"paisrem", "descripcion":"paisrem"},
				{"idtipo":"paisdes", "descripcion":"paisdes"},
				
				{"idtipo":"referenciarem", "descripcion":"referenciarem"},
				{"idtipo":"referenciades", "descripcion":"referenciades"},
				
				{"idtipo":"numinteriorrem", "descripcion":"numinteriorrem"},
				{"idtipo":"numinteriordes", "descripcion":"numinteriordes"},
				{"idtipo":"numexteriorrem", "descripcion":"numexteriorrem"},
				{"idtipo":"numexteriordes", "descripcion":"numexteriordes"},
				
				{"idtipo":"cprem", "descripcion":"cprem"},
				{"idtipo":"telefonorem", "descripcion":"telefonorem"},
				{"idtipo":"empresades", "descripcion":"empresades"},
				{"idtipo":"atenciondes", "descripcion":"atenciondes"},
				{"idtipo":"direcciondes", "descripcion":"direcciondes"},
				{"idtipo":"coloniades", "descripcion":"coloniades"},
				{"idtipo":"municipiodes", "descripcion":"municipiodes"},
				{"idtipo":"estadodes", "descripcion":"estadodes"},
				{"idtipo":"cpdes", "descripcion":"cpdes"},
				{"idtipo":"telefonodes", "descripcion":"telefonodes"},
				{"idtipo":"contenido", "descripcion":"contenido"},
				{"idtipo":"peso", "descripcion":"peso"},
				{"idtipo":"observacion", "descripcion":"observacion"},
				{"idtipo":"multiples", "descripcion":"multiples"},
				{"idtipo":"referencia", "descripcion":"referencia"},
				{"idtipo":"monto", "descripcion":"monto"},
				{"idtipo":"seguro", "descripcion":"seguro"},
				{"idtipo":"acuse", "descripcion":"acuse"},
				{"idtipo":"origen", "descripcion":"origen"},
				{"idtipo":"destino", "descripcion":"destino"},
				{"idtipo":"logo", "descripcion":"logo"},
				{"idtipo":"origen", "descripcion":"origen"},
				{"idtipo":"desgarantia", "descripcion":"desgarantia"},
				{"idtipo":"numcliente", "descripcion":"numcliente"},
				{"idtipo":"singarantia", "descripcion":"singarantia"},
				{"idtipo":"ocurre", "descripcion":"ocurre"},
				{"idtipo":"paqueteria", "descripcion":"paqueteria"},
				{"idtipo":"fuerzaventas", "descripcion":"fuerzaventas"},
				{"idtipo":"ciclo", "descripcion":"ciclo"},
				{"idtipo":"kilometros", "descripcion":"kilometros"},
				
				{"idtipo":"lineaenruta1", "descripcion":"lineaenruta1"},
				{"idtipo":"lineaenruta2", "descripcion":"lineaenruta2"},
				{"idtipo":"lineaenruta3", "descripcion":"lineaenruta3"},
				{"idtipo":"lineaenruta4", "descripcion":"lineaenruta4"},

				{"idtipo":"oficinacontrol", "descripcion":"oficinacontrol"},
				{"idtipo":"descripcionfolioconvenio", "descripcion":"descripcionfolioconvenio"},
				
				{"idtipo":"terminal_ori1", "descripcion":"terminal_ori1"},
				{"idtipo":"terminal_ori2", "descripcion":"terminal_ori2"},
				{"idtipo":"terminal_ori3", "descripcion":"terminal_ori3"},
				{"idtipo":"terminal_ori4", "descripcion":"terminal_ori4"},
				{"idtipo":"terminal_ori5", "descripcion":"terminal_ori5"},
				
				{"idtipo":"terminal_des1", "descripcion":"terminal_des1"},
				{"idtipo":"terminal_des2", "descripcion":"terminal_des2"},
				{"idtipo":"terminal_des3", "descripcion":"terminal_des3"},
				{"idtipo":"terminal_des4", "descripcion":"terminal_des4"},
				{"idtipo":"terminal_des5", "descripcion":"terminal_des5"},
				
				{"idtipo":"precio1", "descripcion":"precio1"},
				{"idtipo":"precio2", "descripcion":"precio2"},
				{"idtipo":"precio3", "descripcion":"precio3"},
				{"idtipo":"precio4", "descripcion":"precio4"},
				{"idtipo":"precio5", "descripcion":"precio5"},
				
				{"idtipo":"adicionales", "descripcion":"adicionales"},
				{"idtipo":"adicional0", "descripcion":"adicional0"},
				{"idtipo":"adicional1", "descripcion":"adicional1"},
				{"idtipo":"adicional2", "descripcion":"adicional2"},
				{"idtipo":"adicional3", "descripcion":"adicional3"},
				{"idtipo":"adicional4", "descripcion":"adicional4"},
				{"idtipo":"adicional5", "descripcion":"adicional5"},
				{"idtipo":"adicional6", "descripcion":"adicional6"},
				{"idtipo":"adicional7", "descripcion":"adicional7"},
				{"idtipo":"adicional8", "descripcion":"adicional8"},
				{"idtipo":"adicional9", "descripcion":"adicional9"},
				
				{"idtipo":"login", "descripcion":"login"},
				{"idtipo":"usuarioimprime", "descripcion":"usuarioimprime"},
				{"idtipo":"idoficina", "descripcion":"idoficina"},
				{"idtipo":"tipoentrega", "descripcion":"idoficina"}
				

			]
});